name = 'Theme name'
license = 'MIT'
licenselink = 'https://github.com/Ced-G/hugo-pixel-world/blob/main/LICENSE'
description = 'A hugo theme with a lively comforting pixel ambience'
summaryLength = 5

# The home page of the theme, where the source can be found
homepage = 'https://github.com/Ced-G/hugo-pixel-world'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Ced-G'
  homepage = 'https://github.com/Ced-G'